POST http://localhost:8081/fame/18970072664/upd
Authorization: Bearer 315ad71268429c47724189467a4f8c407c4c9c5a6816df1b2f5a8454a3c33a91dec89c5a681edf1b2f5a84102b14cd13665adc042b16da54701edf1a391d92542b1cd31f245a84102b14cd1337

{
    "id": "18970072664",
    "name": "邹正良1",
    "quote": "hello world",
    "sex": "男",
    "birthday": "2016-10-10",
    "qq": null,
    "wechat": null,
    "email": null,
    "city": "武汉",
    "rating": 2,
    "height": 175,
    "weight": 0,
    "bust": 0,
    "waist": 0,
    "hip": 0,
    "cup": 0,
    "styles": null,
    "skills": [
        "歌手",
        "主播"
    ],
    "remark": null,
    "sites": null,
    "friends": null
}
