POST http://localhost:8081/fame/18970072664/upd
Authorization: Bearer 315ad71268429c47724189467a4f8c407c4c9c5a6816df1b2f5a8454a3c33a91dec89c5a681edf1b2f5a84102b14cd13665adc042b16da54701edf1a391d92542b1cd31f245a84102b14cd1337

{
    "id": "18970072664",
    "name": "黄田",
    "quote": "C# Geek",
    "sex": "男",
    "birthday": "2016-10-20",
    "qq": null,
    "wechat": null,
    "email": null,
    "city": "南昌",
    "rating": 2,
    "height": 168,
    "weight": 0,
    "bust": 0,
    "waist": 0,
    "hip": 0,
    "cup": 0,
    "styles": null,
    "skills": [
        "演员",
        "主持人"
    ],
    "remark": "0",
    "sites": null,
    "friends": null
}